- name: bug
  description: Something isn't working
  color: d42a34

- name: dependencies
  description: Related with project dependencies
  color: FFD827

- name: documentation
  description: Improvements or additions to documentation
  color: 0677ba

- name: enhancement
  description: New features or code improvements
  color: ffc0cb

- name: good first issue
  description: Easy to solve for newcomers
  color: 62ca50

- name: maintenance
  description: Package and maintenance related
  color: f78c37

- name: graphics
  description: Related with plotting utilities
  color: 000000

- name: support
  description: Further information is requested
  color: 6a32a5

- name: release
  description: Checklist for an upcoming release
  color: ffffff
