# -- Labels based on PR title ------------------------------------------------

'fix':
  - head-branch: ['fix']

'enhancement':
  - head-branch: ['feat']
 

documentation:
- any:
  - changed-files:
    - any-glob-to-any-file: ['doc/source/**/*']
  - head-branch: ['docs', 'doc']

maintenance:
- any: 
  - changed-files:
    - any-glob-to-any-file: ['.github/**/*', 'ruff.toml', '.pre-commit-config.yaml']
  - head-branch: ['maint', 'ci', 'no-ci']

dependencies:
- any:
  - changed-files:
    - any-glob-to-any-file: ['requirements/*']
