exclude = [
    "build",
    "doc/source/conf.py",
]

line-length = 100

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[lint]
select = [
    "D",     # pydocstyle, see https://docs.astral.sh/ruff/rules/#pydocstyle-d
    "E",    # pycodestyle, see https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
    "F",    # pyflakes, see https://docs.astral.sh/ruff/rules/#pyflakes-f
    "I",    # isort, see https://docs.astral.sh/ruff/rules/#isort-i
    "N",    # pep8-naming, see https://docs.astral.sh/ruff/rules/#pep8-naming-n
    "PTH",   # flake8-use-pathlib, https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth
    "TD",   # flake8-todos, https://docs.astral.sh/ruff/rules/#flake8-todos-td
    "W",    # pycodestyle, see https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
]
ignore = [
    "D100",  # Missing docstring in public module
    "D101",  # Missing docstring in public class
    "D102",  # Missing docstring in public method
    "D105",  # Missing docstring in magic method
    "TD002", # Missing author in TODOs comment
    "TD003", # Missing issue link in TODOs comment
]

[lint.pydocstyle]
convention = "numpy"

[lint.isort]
combine-as-imports = true
force-sort-within-sections = true

[lint.mccabe]
max-complexity = 10