exclude = [
    "build",
    "doc/source/conf.py",
]

line-length = 100

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[lint]
select = [
    "E",    # pycodestyle, see https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
    "I",    # isort, see https://docs.astral.sh/ruff/rules/#isort-i
]
ignore = [
    "D",    # pydocstyle, see https://docs.astral.sh/ruff/rules/#pydocstyle-d
    "F",    # pyflakes, see https://docs.astral.sh/ruff/rules/#pyflakes-f
    "N",    # pep8-naming, see https://docs.astral.sh/ruff/rules/#pep8-naming-n
    "PTH",  # flake8-use-pathlib, https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth
    "TD",   # flake8-todos, https://docs.astral.sh/ruff/rules/#flake8-todos-td
    "W",    # pycodestyle, see https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
]

[lint.pydocstyle]
convention = "numpy"

[lint.isort]
combine-as-imports = true
force-sort-within-sections = true

[lint.mccabe]
max-complexity = 10