name: Nightly Documentation Build

on:
  schedule:  # UTC at 0400
    - cron:  '0 4 * * */2' # To run every 3 days
  workflow_dispatch:

env:
  MAIN_PYTHON_VERSION: '3.13'

jobs:
  nightly-docs:
    name: Nightly documentation
    runs-on: ubuntu-22.04
    steps:
      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v3

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-extra latexmk nodejs npm graphviz
          npm install -g @mermaid-js/mermaid-cli

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip tox

      - name: Build HTML documentation
        run: |
          tox -e doc

      - name: Build PDF Documentation
        run: |
          sudo apt update
          sudo apt-get install -y texlive-latex-extra latexmk
          python -m pip install -r requirements/requirements_doc.txt
          make -C doc pdf

      - name: Upload HTML documentation
        uses: actions/upload-artifact@v4.6.1
        with:
          name: HTML-Documentation
          path: doc/_build/html
          retention-days: 7

      - name: Upload PDF Documentation
        uses: actions/upload-artifact@v4.6.1
        with:
          name: PDF-Documentation
          path: doc/_build/latex/pyansys*.pdf
          retention-days: 7

      - name: Deploy to gh-pages
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: .tox/doc_out_html/
          clean: true
          single-commit: true
